auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         10
permalink:        /:categories/:year/:month/:day/:title/

title:           "木兰's 木屋"
url:              http://lanmuwu.com
feed:             /feed.xml
author:
    name:         木兰
    新浪微博:     weibo.com/jiexuangao      
    key:          yigiyigi
description:      "远离尘世的小木屋"
copyright:        "CopryRight 木兰 by GitHub and Jekyll"
headdesc:         "当你启程前往伊萨卡 但愿你的道路漫长， 充满奇迹，充满发现。"
headkeys:         ""
